### ISSUE TITLE
Load libweld.so from $WELD_HOME/target/debug dir in binding.py

### ISSUE THREAD

**Issue by wjliu** [weld-project/weld#125]
Hi,
    When I followed the [tutorial](https://github.com/weld-project/weld/blob/master/docs/tutorial.md) to have a try, an error was triggered as below:

    >>> import numpy
    >>> from hello_weld import *
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "hello_weld.py", line 2, in <module>
        from weld.weldobject import *
      File "build/bdist.linux-x86_64/egg/weld/weldobject.py", line 12, in <module>
      File "build/bdist.linux-x86_64/egg/weld/bindings.py", line 30, in <module>
      File "/root/SkyDiscovery/lib/python2.7/ctypes/__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /data/weld/weld/target/debug/libweld.so: cannot open shared object file: No such file or directory
    >>> 

  I built weld with `cargo build --release` command, and there is no debug directory under target directory.
  I checked the python/weld/bindings.py content as follows:

    home = os.environ["WELD_HOME"]
    if home[-1] != "/":
        home += "/"
    
    path = home + "target/debug/" + path
    
    # Load the Weld Dynamic Library.
    weld = CDLL(path)
 
Is the binding.py just be used in debug mode?  Finding libweld.so automatically may be better.

**Comment by deepakn94** [comment]
Hi @wjliu, thanks for pointing this out! I just pushed a [commit](https://github.com/weld-project/weld/commit/856afd942b11745de1346a13774890aab8f2d22e) to fix this. You will need to re-install the Python modules after pulling the latest changes.
Please let me know if you still run into issues!

**Comment by wjliu** [comment]
HI @deepakn94 , this issue has been resolved, but I encountered another problem when printed my_vector, details info as below:

    >>> print my_vector
    Total time encoding: 2.19345092773e-05
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "hello_weld.py", line 55, in __str__
        v = self.weldobj.evaluate(WeldVec(WeldInt()))
      File "build/bdist.linux-x86_64/egg/weld/weldobject.py", line 166, in evaluate
    TypeError: expected Vec instance, got numpy.ndarray

**Comment by deepakn94** [comment]
Hi @wjliu, I just pushed [another commit](https://github.com/weld-project/weld/commit/db776fab411d1685b8494f286c562a903c171e76) that should fix this (you will need to re-install the Python modules again -- sorry!).
Let me know if this doesn't work for you!

**Comment by wjliu** [comment]
@deepakn94 Thanks, now everything is fine.
