### ISSUE TITLE
[FR] pre-commit integration

### ISSUE THREAD

**Issue by snakescott** [weld-project/weld#154]
pre-commit (http://pre-commit.com/) might be a nice way to wrap up various linters, including the rustfmt that currently executes via ad-hoc build script. pre-commit is python-centric but Rust integrations already exist (e.g., https://github.com/doublify/pre-commit-rust).

Happy to scratch my own itch and submit a PR if there's interest.

**Comment by sppalkia** [comment]
Ah, looks cool; this might be a better thing to do then. Go ahead and submit a PR if you'd like.

**Comment by sppalkia** [comment]
btw, would be cool to integrate something to address #111 in this too!
