### ISSUE TITLE
Cannot materialize a struct of vector builders into a struct of vectors.

### ISSUE THREAD

**Issue by hvanhovell** [weld-project/weld#162]
The following code tries to generate a struct of vectors:
```
|x:i32, ys:vec[i64]|
result(for(ys, {appender[i32], appender[i64]}, |bs, i, y| {merge(bs.$0, x), merge(bs.$1, y)}))
```
However it fails with the following error:
```
Error during LLVM code gen:
Non builder type {appender[i32],appender[i64]} found in GetResult
```
It seems that I cannot materialize a struct of vector builders into a struct of vectors.

**Comment by hvanhovell** [comment]
cc @mateiz

**Comment by sppalkia** [comment]
See #164 - I updated the doc slightly. For now, please call `result` on each struct element individually to get around this; we'll eventually add support for calling `result` on a struct of builders as well.

**Comment by hvanhovell** [comment]
@sppalkia thanks for the quick reaction!
