### ISSUE TITLE
Cannot reuse a weld input vector.

### ISSUE THREAD

**Issue by hvanhovell** [weld-project/weld#163]
I am trying to iterate twice over the same vector, however this fails with a `BadIteratorLength` error. It seems that some of the state of the vector is mutated. The following code current fails:
```
|x:i32, ys:vec[i64]|
let a = result(for(ys, appender[i32], |b, i, y| merge(b, x)));
let b = result(for(ys, appender[i64], |b, i, y| merge(b, y)));
{a, b}
```

**Comment by sppalkia** [comment]
Hmm, I'm not seeing this issue. I added some example code to the repository in #164 if you'd like to take a look at that; make sure a correct length is set in the vector struct.

**Comment by hvanhovell** [comment]
@sppalkia thanks for looking into this. I am calling weld from java, and something might be getting lost in translation. I also just added a similar test case my local weld repo, and that seems to work properly. Lemme take another look at my code.

**Comment by hvanhovell** [comment]
This issue is caused by padding. I was packing `x` (4 bytes) and the `ys`(16 bytes) into a 20 byte struct. Weld - on my platform at least - uses 8 byte alignment and pads the `x` value with an additional 4 bytes. It might be - slightly - useful to put this in the documentation.
