### ISSUE TITLE
Is there no crates for Weld?

### ISSUE THREAD

**Issue by fulmicoton** [weld-project/weld#165]
Is it possible to use Weld from rust as a crate dependency? If so, what is the name of the crate?

**Comment by mateiz** [comment]
Not yet -- you'll have to build it yourself for now but we do want to publish a crate soon.

**Comment by fulmicoton** [comment]
I look forward to it.

**Comment by sppalkia** [comment]
Weld now has a crate: https://crates.io/crates/weld

Thanks to @deepakn94 for doing this!
