### ISSUE TITLE
compile error  error: couldn't read weld/../weld_rt/cpp/libweldrt.bc: No such file or directory (os error 2) how to solve it ?

### ISSUE THREAD

**Issue by wtx626** [weld-project/weld#195]

**Comment by wtx626** [comment]
error: couldn't read weld/../weld_rt/cpp/libweldrt.bc: No such file or directory (os error 2)

**Comment by wtx626** [comment]
error: couldn't read weld/../weld_rt/cpp/libweldrt.bc: No such file or directory (os error 2)
how to solve it ?

**Comment by sppalkia** [comment]
Can you try doing `cargo clean` and then `cargo build` again?

If that doesn't solve the issue, you can do 

```shell
$ cd $WELD_HOME/weld_rt/cpp
$ make
```

This will create `libweldrt.bc`.

**Comment by wtx626** [comment]
@sppalkia 
when I do make in $WELD_HOME/weld_rt/cpp，it shows `clang++-3.9` command is not found . 
So I edit the Makefile in the $WELD_HOME/weld_rt/cpp and change 
`CLANG ?= clang++-${LLVM_VERSION}` to
`CLANG ?= clang-${LLVM_VERSION}` . 
It works well !

**Comment by sppalkia** [comment]
Good to hear you got this working!

**Comment by wtx626** [comment]
@sppalkia But I don't know how weld integrate with Spark .
