### ISSUE TITLE
Nested ifs cause compilation error

### ISSUE THREAD

**Issue by hvanhovell** [weld-project/weld#205]
I am seeing compilation errors when I combine nested ifs with a merger.

For example compilation of the following program:
```
|p: vec[i64]|
let filter = result(for(p,appender[i64], |bs, i, ns|if(ns >= 8767L, if(ns < 9000L, merge(bs, ns), bs), bs)));
result(for(filter, merger[i64, +], |bs2, i2, ns2| merge(bs2, ns2)))
```
fails with the following error:
```
module:919:17: error: '%t.t24' defined with type '%m0.bld.inner*'
  store %v0.bld %t.t24, %v0.bld* %fn3_tmp.4
                ^
```
Compilation of a more dense version of the same program:
```
|p: vec[i64]|
result(for(p,merger[i64, +], |bs, i, ns|if(ns >= 8767L, if(ns < 9000L, merge(bs, ns), bs), bs)))
```
fails with a similar error:
```
module:1114:25: error: '%fn1_tmp.1' defined with type '<4 x i1>*'
  %t.t13 = load i1, i1* %fn1_tmp.1
```
I am posting this because this program is vectorized by weld. That took me by surprise, because I thought both programs would be optimized into the same LLVM program. Maybe we should spin this of in a different issue.

**Comment by sppalkia** [comment]
Posted a fix (#206) for the code generation bug, but you're right -- the reason it vectorizes the If is that it performs a predication transform automatically, which is not necessarily safe (e.g., the condition could be checking into the length of a vector before accessing it). It might be good to make that an optional switch that the user explicitly toggles for now, until we implement a safety check for it (not exactly sure how that would be done).

**Comment by hvanhovell** [comment]
@sppalkia thanks again for the quick turn around!

**Comment by hvanhovell** [comment]
The first case is still broken :(.... They are apparently caused by different bugs. Should I open a new issue?

**Comment by sppalkia** [comment]
No need :) I should have a fix for it soon (also disabling the predication transform by default for the above reason)

**Comment by sppalkia** [comment]
This ended up being a very interesting bug in loop fusion! Should be fixed this time :)
