### ISSUE TITLE
Movielens Perf and Accuracy (Multicore)

### ISSUE THREAD

**Issue by rahulpalamuttam** [weld-project/weld#322]
The movielens workload currently suffers from variable performance when multicore is enabled. 
The workload that varies is the initial hash join step.

The movielens workload also outputs incorrect results.

There's also a duplication of sort function names happening in movielens.
If you move a sort inside of a map function, then the duplication does not happen.
This specifically occurs with the groupby_std which requires a sort on a vector of the following type vec[{vec[i8], vec[f64]}] and is sorted by the first element in each tuple (the string).

These issues are currently not filed against the master branch but the following branch here :
[https://github.com/rahulpalamuttam/weld/tree/fast_single_movielens]

**Comment by jjthomas** [comment]
Variable performance occurs across all versions of the C-based dictionary. Multicore incorrect results start appearing after the initial dictionary commit at #278 and at least by the time we get to the dictionary changes in #297, although we think errors in the following code (which is not affected by #297 but might be affected by #291) is causing the incorrect results at #297. 
`let index_filtered =
      result(
        for(
          zip(%(array)s.$0, %(predicates)s),
          appender,
          |b, i, e| if (e.$1, merge(b, e.$0), b)
        )
      );
    let pivot_filtered =
      map(
        %(array)s.$1,
        |x|
          result(
            for(
              zip(x, %(predicates)s),
              appender,
              |b, i, e| if (e.$1, merge(b, e.$0), b)
            )
          )
      );
    {index_filtered, pivot_filtered, %(array)s.$2}`
