### ISSUE TITLE
Min/max merger compile error

### ISSUE THREAD

**Issue by radujica** [weld-project/weld#327]
`|a: vec[i32]| result(for(a, merger[i32, min], |b: merger[i32, min], i: i64, n: i32| merge(b, n)))`

The above gives: `Compile error: expected commutative binary op in merger but got 'min' (at ...min],|b:merger[i32,min],i:i64,n:i32...)`

However not specifying the function types does not:

`|a: vec[i32]| result(for(a, merger[i32, min], |b, i, n| merge(b, n)))`
`REPL: Program compiled successfully to LLVM`

**Comment by sppalkia** [comment]
Addressed with #329!
