### ISSUE TITLE
dictmerger wrong result for weld.threads >= 2

### ISSUE THREAD

**Issue by mihai-varga** [weld-project/weld#339]
I apologize for opening so many issues, but here's another one:
The `dictmerger` from the following code https://pastebin.com/PibJ18SU produces the wrong result when the number of threads is at least 2. 
The correct output is 3, equal to the number of distinct values in my input array, but the result produced becomes increasingly more wrong as I increase the input size.
 ```
|x:vec[i64]|
let counts = result(
	for(x, dictmerger[i64, i64, +], |b, i, n|
		merge(b, {n, 1L})
	)
);
tovec(counts)
```

**Comment by rahulpalamuttam** [comment]
We should write a test for this.
