### ISSUE TITLE
`brew install llvm@3.8` in the README is removed from homebrew

### ISSUE THREAD

**Issue by chichunchen** [weld-project/weld#362]
Below is the search result from current homebrew on macos. Also, llvm version 6.0 work awesome on my mac for weld!

> brew search llvm
==> Searching local taps...
llvm ✔                              llvm@3.7                            llvm@3.9                            llvm@4                              llvm@5

**Comment by sppalkia** [comment]
Thanks for pointing this out -- we'll upgrade the LLVM version to the latest one soon.

**Comment by sppalkia** [comment]
#368 upgrades the LLVM version 6.0 - closing this.
