### ISSUE TITLE
Sorting on multiple values ~ vec of struct

### ISSUE THREAD

**Issue by radujica** [weld-project/weld#408]
|_inp0: vec[i64], _inp1: vec[f32], _inp2: vec[i64]| 
    let obj101 = (result(
               for(zip(_inp0, _inp1, _inp2),
                   appender[{i64, f32, i64}],
                   |b: appender[{i64, f32, i64}], i: int64, e: {i64, f32, i64}|
                       merge(b, e)
               )    
           ));
    sort(obj101, |e: {i64, f32, i64}| {e.$0, e.$1})

    => Compile error: Sort key function must have scalar or vector return type

Looks like sorting on structs still doesn't work, despite the documentation. Will this be available anytime soon?

**Comment by sppalkia** [comment]
FYI this is merged into llvm-st in #421 + #424

**Comment by sppalkia** [comment]
This is resolved in #438. The sort operator's API now takes a function `|a: T, b: T| => i32` (similar to libc's sorting functions) where the returned `i32` determines whether a > b (returned value > 0), a == b (returned value = 0), or a < b (returned value < 0).
