### ISSUE TITLE
Struct BinOp still not supported

### ISSUE THREAD

**Issue by radujica** [weld-project/weld#418]
This seems to be related to #336 and #408.

    |a: {i64, i64}| if(a == {0L, 2L}, 0L, 2L)

    => Compile error: Illegal type {i64,i64} in BinOp

The necessary code seems to exist: https://github.com/weld-project/weld/blob/bd978e95206ec0e300480d035b9ed2155c3d5ac1/weld/codegen/llvm/llvm.rs#L1940-L1953

yet there's no match for `Struct` in https://github.com/weld-project/weld/blob/bd978e95206ec0e300480d035b9ed2155c3d5ac1/weld/codegen/llvm/llvm.rs#L3154

**Comment by sppalkia** [comment]
This is addressed in the `llvm-st` branch in #421. This branch is now almost feature complete, and we're sketching out a design for adding back threading support as well -- I'll keep this open until that's done, at which point `llvm-st` will likely be merged back into `master`.

**Comment by sppalkia** [comment]
This is resolved in #438
