### ISSUE TITLE
Crate 0.3 is not published on cargo

### ISSUE THREAD

**Issue by fsaintjacques** [weld-project/weld#441]
As opposed to the first line of the landing page, 0.3 is not in cargo. There's also a lack of tags in git (I'd recommend to fix this too).

**Comment by sppalkia** [comment]
Thanks for pointing this out! I'll update this shortly.

Out of curiosity, what are you trying out Weld for? Do let us know if you need any assistance with it!

**Comment by sppalkia** [comment]
The version on Cargo should now be up to date: https://crates.io/crates/weld

**Comment by fsaintjacques** [comment]
I would strongly recommend to tag the version in git.

I'm a developper on Arrow, I wanted to check weld in general, I also note the lack of tpc-h queries referenced in the paper.
