### ISSUE TITLE
failed to run custom build command for weld v0.3.0

### ISSUE THREAD

**Issue by shashwatwork** [weld-project/weld#461]
Hi, 
I'm trying to install weld on my Ubuntu 18.04 machine and I found error like **failed to run custom build command for weld v0.3.0**  while running **cargo build --release**

Please help me to solve this issue.

![image](https://user-images.githubusercontent.com/22785727/61206960-80e0a780-a711-11e9-96d6-87adddbc8894.png)

**Comment by Max-Meldrum** [comment]
Try installing libstdc++ and libstdc++ dev package.

e.g., libstdc++6 and libstdc++-6-dev

**Comment by shashwatwork** [comment]
Thanks Max!! cool
